<?php
/**
 * ChecklistsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChecklistsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChecklistsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2ChecklistChecklistIdChecklistItemChecklistItemIdDelete
     *
     * Delete Checklist Item.
     *
     */
    public function testApiV2ChecklistChecklistIdChecklistItemChecklistItemIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ChecklistChecklistIdChecklistItemChecklistItemIdPut
     *
     * Edit Checklist Item.
     *
     */
    public function testApiV2ChecklistChecklistIdChecklistItemChecklistItemIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ChecklistChecklistIdChecklistItemPost
     *
     * Create Checklist Item.
     *
     */
    public function testApiV2ChecklistChecklistIdChecklistItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ChecklistChecklistIdDelete
     *
     * Delete Checklist.
     *
     */
    public function testApiV2ChecklistChecklistIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ChecklistChecklistIdPut
     *
     * Edit Checklist.
     *
     */
    public function testApiV2ChecklistChecklistIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdChecklistPost
     *
     * Create Checklist.
     *
     */
    public function testApiV2TaskTaskIdChecklistPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
