<?php
/**
 * CommentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2CommentCommentIdDelete
     *
     * Delete Comment.
     *
     */
    public function testApiV2CommentCommentIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CommentCommentIdPut
     *
     * Update Comment.
     *
     */
    public function testApiV2CommentCommentIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdCommentGet
     *
     * Get List Comments.
     *
     */
    public function testApiV2ListListIdCommentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdCommentPost
     *
     * Create List Comment.
     *
     */
    public function testApiV2ListListIdCommentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdCommentGet
     *
     * Get Task Comments.
     *
     */
    public function testApiV2TaskTaskIdCommentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdCommentPost
     *
     * Create Task Comment.
     *
     */
    public function testApiV2TaskTaskIdCommentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdCommentGet
     *
     * Get Chat View Comments.
     *
     */
    public function testApiV2ViewViewIdCommentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdCommentPost
     *
     * Create Chat View Comment.
     *
     */
    public function testApiV2ViewViewIdCommentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
