<?php
/**
 * ListsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2FolderFolderIdListGet
     *
     * Get Lists.
     *
     */
    public function testApiV2FolderFolderIdListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2FolderFolderIdListPost
     *
     * Create a List.
     *
     */
    public function testApiV2FolderFolderIdListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdDelete
     *
     * Delete a List.
     *
     */
    public function testApiV2ListListIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdGet
     *
     * Get List.
     *
     */
    public function testApiV2ListListIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdPut
     *
     * Update a List.
     *
     */
    public function testApiV2ListListIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdTaskTaskIdGet
     *
     * Remove Task From List.
     *
     */
    public function testApiV2ListListIdTaskTaskIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdTaskTaskIdPost
     *
     * Add Task To List.
     *
     */
    public function testApiV2ListListIdTaskTaskIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdListGet
     *
     * Get Folderless Lists.
     *
     */
    public function testApiV2SpaceSpaceIdListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdListPost
     *
     * Create Folderless List.
     *
     */
    public function testApiV2SpaceSpaceIdListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
