<?php
/**
 * TagsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TagsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TagsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2SpaceSpaceIdTagGet
     *
     * Get Space Tags.
     *
     */
    public function testApiV2SpaceSpaceIdTagGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdTagPost
     *
     * Create a Space Tag.
     *
     */
    public function testApiV2SpaceSpaceIdTagPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdTagTagNameDelete
     *
     * Delete a Space Tag.
     *
     */
    public function testApiV2SpaceSpaceIdTagTagNameDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdTagTagNamePut
     *
     * Edit a Space Tag.
     *
     */
    public function testApiV2SpaceSpaceIdTagTagNamePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdTagTagNameDelete
     *
     * Remove Tag From Task.
     *
     */
    public function testApiV2TaskTaskIdTagTagNameDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdTagTagNamePost
     *
     * Add Tag To Task.
     *
     */
    public function testApiV2TaskTaskIdTagTagNamePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
