<?php
/**
 * TasksApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TasksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2ListListIdTaskGet
     *
     * Get Tasks.
     *
     */
    public function testApiV2ListListIdTaskGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdTaskPost
     *
     * Create a Task.
     *
     */
    public function testApiV2ListListIdTaskPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskBulkTimeInStatusTaskIdsGet
     *
     * Get Bulk Tasks' Time in Status.
     *
     */
    public function testApiV2TaskBulkTimeInStatusTaskIdsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdDelete
     *
     * Delete a Task.
     *
     */
    public function testApiV2TaskTaskIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdGet
     *
     * Get Task.
     *
     */
    public function testApiV2TaskTaskIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdPut
     *
     * Update a Task.
     *
     */
    public function testApiV2TaskTaskIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TaskTaskIdTimeInStatusGet
     *
     * Get Task's Time in Status.
     *
     */
    public function testApiV2TaskTaskIdTimeInStatusGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTaskGet
     *
     * Get Filtered Team Tasks.
     *
     */
    public function testApiV2TeamTeamIdTaskGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
