<?php
/**
 * TeamsUserGroupsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamsUserGroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamsUserGroupsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2GroupGet
     *
     * Get Teams.
     *
     */
    public function testApiV2GroupGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2GroupGroupIdDelete
     *
     * Delete a Team.
     *
     */
    public function testApiV2GroupGroupIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2GroupGroupIdPut
     *
     * Update Team.
     *
     */
    public function testApiV2GroupGroupIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdGroupPost
     *
     * Create a Team.
     *
     */
    public function testApiV2TeamTeamIdGroupPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
