<?php
/**
 * TimeTracking20ApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TimeTracking20ApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimeTracking20ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesCurrentGet
     *
     * Get Running Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesCurrentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesGet
     *
     * Get Time Entries Within a Date Range.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesPost
     *
     * Create a Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesStartTimerIdPost
     *
     * Start a Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesStartTimerIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesStopPost
     *
     * Stop Running Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesStopPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTagsDelete
     *
     * Remove Tags From Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTagsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTagsGet
     *
     * Get All Time Entry Tags.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTagsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTagsPost
     *
     * Add Tags to Time Entries.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTagsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTagsPut
     *
     * Rename Time Entry Tags.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTagsPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTimeEntryIdDelete
     *
     * Delete a Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTimeEntryIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTimeEntryIdGet
     *
     * Get Singular Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTimeEntryIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTimerIdHistoryGet
     *
     * Get Time Entry History.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTimerIdHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdTimeEntriesTimerIdPut
     *
     * Update a Time Entry.
     *
     */
    public function testApiV2TeamTeamIdTimeEntriesTimerIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
