<?php
/**
 * ViewsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ClickUp API V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace msn\Test\Api;

use \msn\Configuration;
use \msn\ApiException;
use \msn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ViewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  msn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ViewsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2FolderFolderIdViewGet
     *
     * Get Folder Views.
     *
     */
    public function testApiV2FolderFolderIdViewGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2FolderFolderIdViewPost
     *
     * Create Folder View.
     *
     */
    public function testApiV2FolderFolderIdViewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdViewGet
     *
     * Get List Views.
     *
     */
    public function testApiV2ListListIdViewGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ListListIdViewPost
     *
     * Create List View.
     *
     */
    public function testApiV2ListListIdViewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdViewGet
     *
     * Get Space Views.
     *
     */
    public function testApiV2SpaceSpaceIdViewGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2SpaceSpaceIdViewPost
     *
     * Create Space View.
     *
     */
    public function testApiV2SpaceSpaceIdViewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdViewGet
     *
     * Get Team Views.
     *
     */
    public function testApiV2TeamTeamIdViewGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2TeamTeamIdViewPost
     *
     * Create Team View.
     *
     */
    public function testApiV2TeamTeamIdViewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdDelete
     *
     * Delete a View.
     *
     */
    public function testApiV2ViewViewIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdGet
     *
     * Get View.
     *
     */
    public function testApiV2ViewViewIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdPut
     *
     * Update View.
     *
     */
    public function testApiV2ViewViewIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2ViewViewIdTaskGet
     *
     * Get View Tasks.
     *
     */
    public function testApiV2ViewViewIdTaskGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
